clc;
clear all;
close all;
clc;
clear all;
close all;
f = readtable('Results/all_matlab_train_model3_ref_x_y_xy.csv');
m = 5;
x = f{ :, 2};
y = f{ :, 3};
ref = f{ :, 4};
err_spr_perc_x = f{ :, 22};
err_spr_perc_y = f{ :, 23};
err_spr_perc_xy = f{ :, 24};

err_ann_perc_x = f{ :, 25};
err_ann_perc_y = f{ :, 26};
err_ann_perc_xy = f{ :, 27};

x_u = x(1 : m + 1);
[X] = meshgrid(x_u);
Y = reshape(y, size(X));
Z1 = reshape(err_spr_perc_x, size(X));
Z2 = reshape(err_spr_perc_y, size(X));
Z3 = reshape(err_spr_perc_xy, size(X));

Z4 = reshape(err_ann_perc_x, size(X));
Z5 = reshape(err_ann_perc_y, size(X));
Z6 = reshape(err_ann_perc_xy, size(X));

% figure1;
f1 = figure('Name', 'SPR_X');
surf(X, Y, Z1);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

% hold on;
% figure2;
f2 = figure('Name', 'SPR_Y');
surf(X, Y, Z2);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

hold on;
% figure3;
f3 = figure('Name', 'SPR_XY');
surf(X, Y, Z3);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

hold on;
% figure3;
f4 = figure('Name', 'ANN_X');
surf(X, Y, Z4);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

hold on;
% figure3;
f5 = figure('Name', 'ANN_Y');
surf(X, Y, Z5);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');
hold on;
% figure3;
f6 = figure('Name', 'ANN_XY');
surf(X, Y, Z6);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

exportgraphics(f1, 'Final_figures_surface/model1/model_1_spr_x_aperc.png', 'Resolution', 600);
exportgraphics(f2, 'Final_figures_surface/model1/model_1_spr_y_aperc.png', 'Resolution', 600);
exportgraphics(f3, 'Final_figures_surface/model1/model_1_spr_xy_aperc.png', 'Resolution', 600);
exportgraphics(f4, 'Final_figures_surface/model1/model_1_ann_x_aperc.png', 'Resolution', 600);
exportgraphics(f5, 'Final_figures_surface/model1/model_1_ann_y_aperc.png', 'Resolution', 600);
exportgraphics(f6, 'Final_figures_surface/model1/model_1_ann_xy_aperc.png', 'Resolution', 600);
m = 5;
x = f{ :, 2};
y = f{ :, 3};
ref = f{ :, 4};
err_spr_perc_x = f{ :, 22};
err_spr_perc_y = f{ :, 23};
err_spr_perc_xy = f{ :, 24};

err_ann_perc_x = f{ :, 25};
err_ann_perc_y = f{ :, 26};
err_ann_perc_xy = f{ :, 27};

x_u = x(1 : m + 1);
[X] = meshgrid(x_u);
Y = reshape(y, size(X));
Z1 = reshape(err_spr_perc_x, size(X));
Z2 = reshape(err_spr_perc_y, size(X));
Z3 = reshape(err_spr_perc_xy, size(X));

Z4 = reshape(err_ann_perc_x, size(X));
Z5 = reshape(err_ann_perc_y, size(X));
Z6 = reshape(err_ann_perc_xy, size(X));

% figure1;
f1 = figure('Name', 'SPR_X');
surf(X, Y, Z1);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

% hold on;
% figure2;
f2 = figure('Name', 'SPR_Y');
surf(X, Y, Z2);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

hold on;
% figure3;
f3 = figure('Name', 'SPR_XY');
surf(X, Y, Z3);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

hold on;
% figure3;
f4 = figure('Name', 'ANN_X');
surf(X, Y, Z4);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

hold on;
% figure3;
f5 = figure('Name', 'ANN_Y');
surf(X, Y, Z5);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');
hold on;
% figure3;
f6 = figure('Name', 'ANN_XY');
surf(X, Y, Z6);
view(2);
set(gca, 'FontSize', 15);
shading(gca, 'interp');
a = colorbar;
ylabel(a, 'Absolute Percentage Error (%)', 'FontSize', 15);
xlabel('X-coordinate');
ylabel('Y-coordinate');
zlabel('Percentage Error');

exportgraphics(f1, 'Final_figures_surface/model3/model_3_spr_x_aperc.png', 'Resolution', 600);
exportgraphics(f2, 'Final_figures_surface/model3/model_3_spr_y_aperc.png', 'Resolution', 600);
exportgraphics(f3, 'Final_figures_surface/model3/model_3_spr_xy_aperc.png', 'Resolution', 600);
exportgraphics(f4, 'Final_figures_surface/model3/model_3_ann_x_aperc.png', 'Resolution', 600);
exportgraphics(f5, 'Final_figures_surface/model3/model_3_ann_y_aperc.png', 'Resolution', 600);
exportgraphics(f6, 'Final_figures_surface/model3/model_3_ann_xy_aperc.png', 'Resolution', 600);
